name: tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.11'
      - name: Gradle tests
        run: ./gradlew check
